### ISSUE TITLE
compile fails 2022/12/05

### ISSUE THREAD

**Issue by Corsaire01** [AdrianKoshka/macc-uefi-build-script#12]
Compile fails on Ubuntu 22.10
Using cross-compile instructions

Here is the end of the log after the tests:

```
----------------------------------------------------------------------
Ran 302 tests in 3.458s

OK
make[1]: Leaving directory '/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/BaseTools/Tests'
make: Leaving directory '/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/BaseTools'
Using EDK2 in-source Basetools
WORKSPACE: /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b
EDK_TOOLS_PATH: /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/BaseTools
CONF_PATH: /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/Conf
Copying $EDK_TOOLS_PATH/Conf/build_rule.template
     to /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/Conf/build_rule.txt
Copying $EDK_TOOLS_PATH/Conf/tools_def.template
     to /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/Conf/tools_def.txt
Copying $EDK_TOOLS_PATH/Conf/target.template
     to /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/Conf/target.txt
Build environment: Linux-5.19.0-23-generic-x86_64-with-glibc2.36
Build start time: 21:37:14, Dec.05 2022

WORKSPACE        = /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b
PACKAGES_PATH    = /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2:/home/stranche/macc-uefi-build-script-main/actions/scrip                                                                             ts/e2b/edk2-platforms:/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2-non-osi
EDK_TOOLS_PATH   = /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/BaseTools
CONF_PATH        = /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3


Architecture(s)  = AARCH64
Build target     = RELEASE
Toolchain        = GCC5

Active Platform          = /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2-platforms/Platform/SolidRun/Armada80x0McBin/Arma                                                                             da80x0McBin.dsc

Processing meta-data ........####.... done!
Building ... /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf                                                                              [AARCH64]
Building ... /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Library/BaseStackCheckLib/BaseStackCheckLib.inf [AARCH6                                                                             4]
Trim --asm-file -o /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/Lib                                                                             rary/CompilerIntrinsicsLib/CompilerIntrinsicsLib/OUTPUT/AArch64/Atomics.i -i /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Bui                                                                             ld/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib/OUTPUT/inc.lst /home/stranche/macc-u                                                                             efi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Library/CompilerIntrinsicsLib/AArch64/Atomics.S
"gcc"   -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sectio                                                                             ns -fdata-sections -DSTRING_ARRAY_NAME=BaseStackCheckLibStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array                                                                             -bounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-                                                                             address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -mcmodel=small -flto -Wno-unused-but-set-variable -Wno                                                                             -unused-const-variable -D ENABLE_MD5_DEPRECATED_INTERFACES -mstrict-align -mgeneral-regs-only -c -o /home/stranche/macc-uefi-build-script-main/                                                                             actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/MdePkg/Library/BaseStackCheckLib/BaseStackCheckLib/OUTPUT/./BaseStackChe                                                                             ckGcc.obj -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Library/BaseStackCheckLib -I/home/stranche/macc-uefi-bui                                                                             ld-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/MdePkg/Library/BaseStackCheckLib/BaseStackCheckLib/DEBUG                                                                              -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/e                                                                             dk2/MdePkg/Include -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Test/UnitTest/Include -I/home/stranche/macc-uef                                                                             i-build-script-main/actions/scripts/e2b/edk2/MdePkg/Include/AArch64 /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/                                                                             Library/BaseStackCheckLib/BaseStackCheckGcc.c
Building ... /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.inf [AARCH64]
"gcc"   -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sectio                                                                             ns -fdata-sections -DSTRING_ARRAY_NAME=ArmArchTimerLibStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-b                                                                             ounds -include AutoGen.h -fno-common -mlittle-endian -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-ad                                                                             dress -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -mcmodel=small -flto -Wno-unused-but-set-variable -Wno-u                                                                             nused-const-variable -D ENABLE_MD5_DEPRECATED_INTERFACES -mstrict-align -mgeneral-regs-only -c -o /home/stranche/macc-uefi-build-script-main/ac                                                                             tions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib/OUTPUT/./ArmArchTimerLib.ob                                                                             j -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Library/ArmArchTimerLib -I/home/stranche/macc-uefi-build-script-                                                                             main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib/DEBUG -I/home/stranc                                                                             he/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Inc                                                                             lude -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Test/UnitTest/Include -I/home/stranche/macc-uefi-build-script                                                                             -main/actions/scripts/e2b/edk2/MdePkg/Include/AArch64 -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/EmbeddedPkg -I/home                                                                             /stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/EmbeddedPkg/Include -I/home/stranche/macc-uefi-build-script-main/actions/scripts                                                                             /e2b/edk2/ArmPkg -I/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Include /home/stranche/macc-uefi-build-script-mai                                                                             n/actions/scripts/e2b/edk2/ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.c
Building ... /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint.inf [                                                                             AARCH64]
gcc: error: unrecognized command-line option ‘-mlittle-endian’
gcc: error: unrecognized command-line option ‘-mstrict-align’; did you mean ‘-Wstrict-aliasing’?
make: *** [GNUmakefile:293: /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/A                                                                             rmPkg/Library/ArmArchTimerLib/ArmArchTimerLib/OUTPUT/ArmArchTimerLib.obj] Error 1


build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/L                                                                             ibrary/ArmArchTimerLib/ArmArchTimerLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/MdePkg/L                                                                             ibrary/BaseStackCheckLib/BaseStackCheckLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/MdePkg/L                                                                             ibrary/UefiDriverEntryPoint/UefiDriverEntryPoint]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/AARCH64/ArmPkg/L                                                                             ibrary/CompilerIntrinsicsLib/CompilerIntrinsicsLib]


build.py...
 : error F002: Failed to build module
        /home/stranche/macc-uefi-build-script-main/actions/scripts/e2b/edk2/ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.inf [AARCH64, GCC5,                                                                              RELEASE]

- Failed -
Build end time: 21:37:26, Dec.05 2022
Build total time: 00:00:12

ls: cannot access 'Build/Armada80x0McBin-AARCH64/RELEASE_GCC5/FV/ARMADA_EFI.fd': No such file or directory
Traceback (most recent call last):
  File "/home/stranche/macc-uefi-build-script-main/actions/scripts/kickoff.py", line 52, in <module>
    main()
  File "/home/stranche/macc-uefi-build-script-main/actions/scripts/kickoff.py", line 48, in main
    edk2_build()
  File "/home/stranche/macc-uefi-build-script-main/actions/scripts/kickoff.py", line 33, in edk2_build
    buildProcess = subprocess.run("./build.sh", shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './build.sh' returned non-zero exit status 2.
```

**Comment by AdrianKoshka** [comment]
Compilation failures are out of the scope of this project, I just provide scripts that _should_ run the build process for you, whether it works or not isn't guaranteed.
